### ISSUE TITLE
favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by wonkpentink** [beritagarid/monitoring-traffic-office#6]
error message 👍 

<img width="695" alt="screen shot 2016-04-12 at 2 58 09 pm" src="https://cloud.githubusercontent.com/assets/222578/14453488/5cefb830-00bf-11e6-994d-cb1cb2d1435d.png">

bikinin ico nya bos favicon.ico not found

**Comment by trioputracb** [comment]
#9
